defmodule LmapController.Agents do
  alias LmapController.Repo
  alias LmapController.Agents.MeasurementAgent

  # Create or update the reported state of a Measurement Agent (MA) in the database
  # OBS: We don't have a :desired_config field in the reported state, because the MA doesn't report its desired config to the LMAP Controller. The desired config is set by the LMAP Controller (received by the orchestrator) and stored in the database, but it's not part of the things sent by the MA.
  def update_reported_state(agent_id, reported_state) do
    attrs = %{
      # id: index automatically generated by Ecto, of type :bigint
      agent_id: agent_id,
      reported_state: reported_state,
      last_seen_at: DateTime.utc_now()
      # inserted_at: automatically generated by Ecto by timestamps(type: :utc_datetime_usec) on the migration.
      # updated_at: automatically generated by Ecto by timestamps(type: :utc_datetime_usec) on the migration.
    }

    case Repo.get_by(MeasurementAgent, agent_id: agent_id) do
      nil ->
        %MeasurementAgent{}
        |> MeasurementAgent.changeset(attrs)
        |> Repo.insert()

      # Struct of the MeasurementAgent is returned, so we can use it to update the desired_config field
      measurement_agent ->
        measurement_agent
        |> MeasurementAgent.changeset(attrs)
        |> Repo.update()
    end
  end

  # Update the desired configuration for a Measurement Agent (MA) in the database
  def update_desired_config(agent_id, desired_config) do
    case Repo.get_by(MeasurementAgent, agent_id: agent_id) do
      nil ->
        {:error, :agent_not_found}

      # Struct of the MeasurementAgent is returned, so we can use it to update the desired_config field
      measurement_agent ->
        measurement_agent
        |> MeasurementAgent.changeset(%{desired_config: desired_config})
        |> Repo.update()
    end
  end
end
